name: data_sc_tester
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: "2.17.3"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.5
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/log.png"
  image_path_android: "assets/images/log.png"
  image_path_ios: "assets/images/log.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/log.png"
  adaptive_icon_foreground: "assets/images/log.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/android_new_logo.jpg
    - assets/images/facebook.png
    - assets/images/github.png
    - assets/images/google.png
    - assets/images/illustration-1.png
    - assets/images/illustration-2.png
    - assets/images/log.png
    - assets/images/person.jpg
    - assets/images/profil.jpeg
flutter_native_splash:
  color: "#accffc"
  #91BEF7
  image: assets/images/log.png
