name: data_sc_tester
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: "2.17.3"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.5
  flutter_icons: ^1.1.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/log.png"

flutter_native_splash:
  color: "#91BEF7"
#  image: assets/images/log.png
flutter:
  uses-material-design: true
